name: Compile Application

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.300'
          include-prerelease: true

      - name: Build API
        run: |
         dotnet build Backend --configuration "Release"
        
      - name: Make deploy folder
        run: |
         mkdir deploy

      - name: Publish API
        run: |
         dotnet publish Backend -c "Release" -o deploy
      
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.13.0'
      
      - name: Compile Frontend
        run: |
         npm ci
         npm run build
        working-directory: Frontend
      
      - name: Merge Frontend into Deployment Folder
        run: |
         xcopy Frontend\dist\* deploy\wwwroot /E

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: OrcApp
          path: deploy
